[package]
name = "carphys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
lazy_static = "1.4.0"

[dev-dependencies]
approx = "0.5.1"
